# Documentation
server {
    listen 8080;
    root daynight;
	server_name DoxygenDocs;

	# catch all
    location / {
		root daynight;
        autoindex off;
		index index.html;
        allow_methods GET;
    }
}
